language: php

services:
  - mysql

php:
  - 7.1

before_script:
  - cp .env.testing .env
  - composer install --no-interaction
  - php artisan key:generate --no-interaction
  - php artisan jwt:secret --force
  - php artisan migrate --seed --no-interaction

script:
  - php artisan test --env=testing
